### PR TITLE
add photo

### PR DESCRIPTION
**Pull request by Islast**

### CODE REVIEW

**Comment by KirstieJane** [comment]
(Is this a wip? Should I comment)

(I'll do it anyway - can you make the file ending `jpg` not `JPG`? It sometimes makes things complicated going forwards)

**Comment by Islast** [comment]
it done :sunflower:

**Comment by KirstieJane** [comment]
Hey @Islast - I think this can be merged right? I think the blog post has its own copy of these files so nothing should break 😄

**Comment by Islast** [comment]
Yep! merged

**Pull request merged**
