### PR TITLE
Update Kirstie's where file

### PR DESCRIPTION
**Pull request by KirstieJane**
Hi @lzdh and @Islast - this is a little update to update my where file.

The last few months aren't filled in yet, and I still might be on strike over the next two weeks (M-Th next week and M-F the week after) but *hopefully* not. We'll see.

Once you've reviewed, please merge!

### CODE REVIEW

**Comment by Islast** [comment]
screenshot from 2018-03-01 22-11-31

Looks great

**Comment by KirstieJane** [comment]
Oh my goodness that's spectacular. It looks ok for me (including when rendered) and given how amazing it is I'm tempted to keep the brains to make any linux users that stop on by smile!

Let me know if it looks like then when rendered as markdown as that might be a little too much and I'll change to the flag for Singapore :)

**Comment by KirstieJane** [comment]
Can I share this picture on the twitters?

**Comment by Islast** [comment]
Yeah, go ahead. I think it might be a firefox bug for rendering emojis

**Comment by lzdh** [comment]
😂😂😂that looks amazing!

**Pull request merged**
