### PR TITLE
Update Kirstie's weekly meetings | 18-24 March

### PR DESCRIPTION
**Pull request by KirstieJane**
Woo - actually managed to write up a 1 week summary! 🚀 

Open for reviews. I'll merge when I have a couple 😄

### CODE REVIEW

**Comment by sprak0323** [comment]
I always admire people who can parallelly do many works, like you 👍 

BTW, there is a Chinese verb (also a kind of white wine) called '舍得'. '舍' solely means 'abandon' and '得' solely means 'achieve', '舍得' together is a new word means 'be willing to part with' or 'not begrudge', it suggests that we can achieve more if we can abandon something unimportant. 

Hope you can persistently '舍'  something  and '得' what's more important for you and more free time! although it's really not easy ~

Support the merge!

**Comment by KirstieJane** [comment]
Aaaaaah you're both so lovely! Thank you! Merging now ✨

**Comment by KirstieJane** [comment]
Oh - update. Neither of you actually "reviewed" according to GitHub.

(You "just" commented!)

That means I can't merge because this repository requires one approval review. There should be a green button that says "Review" somewhere at the top or the right hand side of the page....

(Thank you both for working through this with me. It's a LOT to wrap your head around!)

**Comment by maxinemack** [comment]
You may now merge.... i believe....

**Comment by maxinemack** [comment]
> I always admire people who can parallelly do many works, like you 👍
> 
> BTW, there is a Chinese verb (also a kind of white wine) called '舍得'. '舍' solely means 'abandon' and '得' solely means 'achieve', '舍得' together is a new word means 'be willing to part with' or 'not begrudge', it suggests that we can achieve more if we can abandon something unimportant.
> 
> Hope you can persistently '舍' something and '得' what's more important for you and more free time! although it's really not easy ~
> 
> Support the merge!

**Comment by maxinemack** [comment]
oh no i just clicked something weird.... balls

**Comment by KirstieJane** [comment]
I've done this "close the PR" thing SO MANY TIMES!!

Thank you @maxinemack! MERGING!

**Pull request merged**
