### PR TITLE
added example licensing sentence

### PR DESCRIPTION
**Pull request by daniellecrobinson**
and changed license to CC BY 4.0

Check it out!

### CODE REVIEW

**Comment by KirstieJane** [comment]
@daniellecrobinson - see if you like the changes I made - if you do - go ahead and merge!

**Comment by daniellecrobinson** [comment]
girl, you mist merge 

![]https://media.giphy.com/media/3oz8xr44L9OeTIw1j2/giphy.gif

**Comment by daniellecrobinson** [comment]
Girl, I don't have write access, you must merge...

**Comment by KirstieJane** [comment]
Haaahahahaha! I forgoooooot!

DONE! MERGED! Dr Mystery will have a lab guide yet 🌟

**Comment by KirstieJane** [comment]
Closes #46

**Pull request merged**
